workflow:
  rules:
    # Rules taken from official docs to avoid duplicated pipelines
    - if: $CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS && $CI_PIPELINE_SOURCE == "push"
      when: never
    - when: always

stages:
  - build
  - test
  - deploy

variables:
  GIT_SUBMODULE_DEPTH: 1
  bb5_build_dir: "pipeline"  # Notice: this keeps build dir among jobs! no artifacts needed
  bb5_account: proj12
  bb5_partition: prod_small
  bb5_cpus_per_task: 2


.test:
  stage: test
  tags:
    - bb5_map
  before_script:
    - export TMPDIR="$TMPDIR/$CI_PIPELINE_ID"


test_combined_model:
  extends: .test
  variables:
    GIT_SUBMODULE_STRATEGY: normal
    bb5_cpus_per_task: 2  # for parallel make
    bb5_constraint: cpu
  script:
    - mkdir -p $HOME
    - ln -s ~bbpcihpcproj12/.ssh $HOME/
    - module load unstable python neuron
    - ./model_manager.py model_config.json
    - nrnivmodl build/ALL/mod
    - ./x86_64/special -c 'print "Hello world!"'
  rules:
    - if: '$CI_PIPELINE_SOURCE != "pipeline"'

