name: Test model compilation

on:
  push:
    branches: ['main']
  pull_request:

env:
  SONATA_REPORT_VERSION: '1.2.3'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        model: ['hippocampus', 'neocortex', 'thalamus']
        # FIXME The coreneuron parameter is ignored for now;  PyPI builds of NEURON do not
        # include CoreNEURON.
        coreneuron: ['ON']
        metabolism: ['OFF']
        ngv: ['OFF']
        plasticity: ['OFF']
        v5: ['OFF']
        include:
          - model: 'neocortex'
            coreneuron: 'OFF'
            metabolism: 'ON'
            ngv: 'ON'
            plasticity: 'OFF'
            v5: 'OFF'
          - model: 'neocortex'
            coreneuron: 'ON'
            metabolism: 'OFF'
            ngv: 'OFF'
            plasticity: 'ON'
            v5: 'OFF'
          - model: 'neocortex'
            coreneuron: 'ON'
            metabolism: 'OFF'
            ngv: 'OFF'
            plasticity: 'OFF'
            v5: 'ON'

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    - name: Install dependencies
      run: |
        sudo apt-get update -y
        sudo apt-get install libopenmpi-dev libhdf5-dev
        python -m pip install --upgrade pip
        python -m pip install NEURON-nightly neurodamus
    - name: Install dependencies
      run: |
        gh repo clone BlueBrain/libsonatareport ../reports/src -- --recursive --shallow-submodules --branch ${{ env.SONATA_REPORT_VERSION }}
        cmake \
          -B ../reports/build \
          -S ../reports/src \
          -DCMAKE_INSTALL_PREFIX=../reports/install \
          -DSONATA_REPORT_ENABLE_SUBMODULES=ON \
          -DSONATA_REPORT_ENABLE_TEST=OFF
        cmake --build ../reports/build
        cmake --install ../reports/build
      env:
        GH_TOKEN: ${{ github.token }}
    - name: Configure models
      run: |
        export CC=$(which mpicc)
        export CXX=$(which mpicxx)
        DATADIR=$(python -c "import neurodamus; from pathlib import Path; print(Path(neurodamus.__file__).parent / 'data')")
        cmake -B build -S . \
          -DCMAKE_INSTALL_PREFIX=$PWD/install \
          -DCMAKE_PREFIX_PATH=$PWD/../reports/install \
          -DNEURODAMUS_CORE_DIR=${DATADIR} \
          -DNEURODAMUS_ENABLE_CORENEURON=OFF \
          -DNEURODAMUS_MECHANISMS=${{ matrix.model }} \
          -DNEURODAMUS_NCX_METABOLISM=${{ matrix.metabolism }} \
          -DNEURODAMUS_NCX_NGV=${{ matrix.ngv }} \
          -DNEURODAMUS_NCX_PLASTICITY=${{ matrix.plasticity }} \
          -DNEURODAMUS_NCX_V5=${{ matrix.v5 }}
    - name: Build and install models
      run: |
        cmake --build build
        cmake --install build
        ls -R install
